def rebaseNeeded       = "-1"
def allRecipientEmails = ""

pipeline {
    agent any

    environment {
        GITHUB_USER_OR_ORG_NAME = sh(script: 'echo ${CHANGE_URL:-alifsemi}    | sed -E "s#https://github.com/([^/]+)/([^/]+)/.*#\\1#"', returnStdout: true).trim()
        GITHUB_REPO_NAME        = sh(script: 'echo ${CHANGE_URL:-zephyr_alif} | sed -E "s#https://github.com/([^/]+)/([^/]+)/.*#\\2#"', returnStdout: true).trim()
        CHANGE_TARGET           = sh(script: 'echo ${CHANGE_TARGET:-main}', returnStdout: true).trim()
        GITHUB_TOKEN = credentials('rajranjan_github_classic')
        PATH="${env.WEST_BIN_PATH}:${env.PATH}"
    }

    options {
        skipDefaultCheckout(true)
    }

    stages {
        stage('Install Dependencies') {
            steps {
                script {
                    sh """#!/bin/bash -xe
                    echo -e "✔️ None."
                    """
                }
            }
        }

        stage('Display Environment Variables') {
            steps {
                script {
                    sh """#!/bin/bash -xe
                        printenv
                        echo -e "🛠️ $PATH"
                        echo -e "✔️ Displayed all environment setting."
                    """
                }
            }
        }

        stage('checkout') {
            steps {
                cleanWs()
                echo "⏳ Checking out '${GITHUB_REPO_NAME}' repo..."

                dir("${GITHUB_REPO_NAME}") {
                    checkout scm
                }

                script {
                    catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
                        sh '''#!/bin/bash
                        set -xe
                        echo -e "✅ Checkout is completed "${GITHUB_REPO_NAME}"."

                        if [ ! -d "${GITHUB_REPO_NAME}" ] ; then
                            echo -e "🚫 ${GITHUB_REPO_NAME} directory didn't found."
                            exit -1
                        fi
                        '''
                    }
                }

                script {
                    rebaseNeeded = sh(
                        script: '''#!/bin/bash
                            set -xe
                            cd ${GITHUB_REPO_NAME}
                            git fetch origin refs/heads/${CHANGE_TARGET}:refs/remotes/origin/${CHANGE_TARGET}

                            if ! git rebase origin/${CHANGE_TARGET} ; then
                                echo -e "Rebase could not happen successfully"
                                exit 1
                            fi

                            commitCnt=$(git rev-list --count origin/${CHANGE_TARGET}..HEAD)
                            commits=$(git log -n ${commitCnt} --pretty=format:"%H")

                            if [[ "$commitCnt" -lt "1" ]] ; then
                                echo 0
                                exit 0
                            fi

                            firstCommit=$(git log -n 1 --pretty=format:"%H")
                            firstCommit_author_name=$(git show -s --format="%an" "$firstCommit")
                            firstCommit_author_email=$(git show -s --format="%ae" "$firstCommit")
                            firstCommit_body=$(git show -s --format="%b" "$firstCommit" | tail -n +1 | awk '!/^[A-Za-z-]+:/ {print}' | sed '/^$/d')
                            parentCnt=$(git log -n 1 --pretty=format:"%p"  | wc -w)

                            if [[ "$firstCommit_author_name" == "Jenkins" || "$firstCommit_author_email" == "nobody@nowhere" || "$firstCommit_body" == "*Merge commit \'$firstCommit\' into HEAD*" || "$parentCnt" -gt "1" ]] ; then
                                git reset --soft HEAD~1
                                echo 1
                            else
                                echo 0
                            fi
                            ''',
                        returnStdout: true
                    ).trim()
                     echo "🎯 rebase needed: [${rebaseNeeded}]..."
                }
            }
        }

        stage('Get PR Message/Authors') {
            steps {
                script {
                    allRecipientEmails = sh(
                        script: '''#!/bin/bash
                            set -xe
                            cd ${GITHUB_REPO_NAME}
                            commitCnt=$(git rev-list --count origin/${CHANGE_TARGET}..HEAD)

                            # Get all author emails for this PR
                            culpritEmails=$(git log -n $commitCnt --pretty=format:'%ae' | sort | uniq | paste -sd";" -)

                            # Replace all commas with semicolons
                            defaultEmails=$(echo "$DEFAULT_OWNER_EMAILS" | tr ',' ';')

                            all_emails="$culpritEmails;$defaultEmails;test@st.com"
                            all_unique_emails=$(echo "$all_emails" | tr ';' '\n' | grep -v '^$' | sort -u | paste -sd ";" -)
                            echo "$all_unique_emails" | tr ';' '\n' | grep '@alifsemi.com$' | paste -sd';' -
                        ''',
                        returnStdout: true
                    ).trim()
                    echo "📤 Mail will be sent to: [${allRecipientEmails}]..."
                }
            }
        }

        stage('CheckPatch and Commit Message Validation') {
            steps {
                script {
                    withCredentials([string(credentialsId: 'rajranjan-alifsemi', variable: 'GITHUB_TOKEN')]) {
                        sh '''
                        for label in BUILD_AWAITING BUILD_FAILED BUILD_PASSED CHECKPATCH_FAILED
                        do
                            curl -sS -o /dev/null -X DELETE "https://api.github.com/repos/${GITHUB_USER_OR_ORG_NAME}/${GITHUB_REPO_NAME}/issues/${CHANGE_ID}/labels/$label" \
                              -H "Authorization: Bearer ${GITHUB_TOKEN}" \
                              -H "Content-Type: text/plain"
                        done

                        for id in $(curl -sS -X GET -H "Authorization: Bearer $GITHUB_TOKEN" \
                          https://api.github.com/repos/${GITHUB_USER_OR_ORG_NAME}/${GITHUB_REPO_NAME}/issues/${CHANGE_ID}/comments \
                          | jq -r '.[] | select(.body | contains("✏️ PLEASE UPDATE MANIFEST FILE IN SDK-ALIF REPO WITH SHA/COMMIT-ID/PULL-NUMBER ✏️")) | .id')
                        do
                          curl -sS -X DELETE \
                            -H "Authorization: Bearer $GITHUB_TOKEN" \
                            https://api.github.com/repos/${GITHUB_USER_OR_ORG_NAME}/${GITHUB_REPO_NAME}/issues/comments/$id
                        done
                        '''
                    }
                    catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
                        sh """#!/bin/bash
                        set -xe
                        cd \${GITHUB_REPO_NAME}

                        commitCnt=\$(git rev-list --count origin/${CHANGE_TARGET}..HEAD)
                        totalCommitCnt=\$(git rev-list --count origin/${CHANGE_TARGET})

                        if [[ "\$totalCommitCnt" -lt "\$commitCnt" ]] ; then
                            checkGitLog=\${commitCnt}
                        else
                            checkGitLog=6
                        fi
                        git log -\${checkGitLog}

                        echo -e "🎯 we have \$commitCnt commits in \$CHANGE_TARGET review"
                        if [[ "\${commitCnt}" =~ ^[0-9]+\$ && "\${commitCnt}" -gt "0" ]] ; then
                            git format-patch -\${commitCnt}
                            check_patch_output=\$(./scripts/checkpatch.pl --patch *.patch)
                            echo -e "\$check_patch_output"
                            check_patch_output_summary=\$(echo "\$check_patch_output" | grep ".patch total:")
                            echo -e "\$check_patch_output_summary"

                            check_patch_errors=0
                            check_patch_warnings=0
                            check_patch_lines=0

                            while read -r line; do
                              # Extract numbers using regex or field parsing
                              err=\$(echo "\$line"  | awk '{for(i=1;i<=NF;i++) if(\$i=="total:") print \$(i+1)}')
                              warn=\$(echo "\$line" | awk '{for(i=1;i<=NF;i++) if(\$i=="errors,") print \$(i+1)}')
                              ln=\$(echo "\$line"   | awk '{for(i=1;i<=NF;i++) if(\$i=="warnings,") print \$(i+1)}')

                              if [[ "\$err" =~ ^[0-9]+\$ ]]; then
                                check_patch_errors=\$((check_patch_errors + err))
                              else
                                echo "Skipping non-numeric error: \$err"
                              fi

                              if [[ "\$warn" =~ ^[0-9]+\$ ]]; then
                                check_patch_warnings=\$((check_patch_warnings + warn))
                              else
                                echo "Skipping non-numeric warning: \$warn"
                              fi

                              if [[ "\$ln" =~ ^[0-9]+\$ ]]; then
                                check_patch_lines=\$((check_patch_lines + ln))
                              else
                                echo "Skipping non-numeric lines: \$ln"
                              fi

                            done <<< "\$check_patch_output_summary"

                            echo -e "🎯Check-Patch has=> Errors: \${check_patch_errors} Warnings: \${check_patch_warnings}, Lines: \${check_patch_lines}\n\n"

                            pr_checker_log=\$(${VALIDATION_SCRIPT_DIR}/pr_commit_checker.sh  \${commitCnt})
                            pr_checker_err=\$?
                            echo -e "🎯PR Checker=>\n\$pr_checker_log"

                            gitlint_log=\$(git log -\${commitCnt} --pretty=%B | gitlint 2>&1)
                            if [ -n "\$gitlint_log" ] ; then
                                gitlint_err=1
                                echo -e "🎯GITLINT log=>\n\$gitlint_log"
                            else
                               gitlint_err=0
                            fi
                        else
                            gitlint_err=0
                            pr_checker_err=0
                            check_patch_errors=0
                        fi
                        echo -e " 🏆Git Rebase Needed  =>  ${rebaseNeeded}"
                        echo -e " 🏆GitLint Result     =>  \${gitlint_err}"
                        echo -e " 🏆PR Checker  Result =>  \${pr_checker_err}"
                        echo -e " 🏆Check-Patch Result =>  Error: \$check_patch_errors, Warnings: \$check_patch_warnings"
                        """
                    }
                }
            }
        }
    }

    post {
        failure {
            echo "🚫 Build failed. Sending email..."
            script {
                emailext (
                    subject: "🚨 Jenkins Job Failed: ${env.JOB_NAME} [${env.BUILD_NUMBER}]",
                    body: """
                       <p>Build failed for job: <b>${env.CHANGE_URL}</b></p>
                       <p>Build Number: <b>${env.BUILD_NUMBER}</b></p>
                       <p>View details: <a href="${env.BUILD_URL}">${env.BUILD_URL}</a></p>
                    """,
                    to : "${allRecipientEmails}",
                    mimeType: 'text/html'
                )
                withCredentials([string(credentialsId: 'rajranjan-alifsemi', variable: 'GITHUB_TOKEN')]) {
                    sh '''
                    curl -sS -o /dev/null -X POST "https://api.github.com/repos/${GITHUB_USER_OR_ORG_NAME}/${GITHUB_REPO_NAME}/issues/${CHANGE_ID}/labels" \
                      -H "Authorization: Bearer ${GITHUB_TOKEN}" \
                      -H "Content-Type: text/plain" \
                      -d '["CHECKPATCH_FAILED"]'
                    '''
                }
            }
        }

        success {
            echo "🟢 PLEASE UPDATE CORRESPONDING SHA/COMMIT-ID IN MANIFEST FILE OF ALIF_SDK 🟢"
            script {
                withCredentials([string(credentialsId: 'rajranjan-alifsemi', variable: 'GITHUB_TOKEN')]) {
                    sh '''
                    curl -sS -o /dev/null -X POST "https://api.github.com/repos/${GITHUB_USER_OR_ORG_NAME}/${GITHUB_REPO_NAME}/issues/${CHANGE_ID}/comments" \
                      -H "Authorization: Bearer ${GITHUB_TOKEN}" \
                      -H "Content-Type: application/json" \
                      -d '{
                            "body": "✏️ PLEASE UPDATE MANIFEST FILE IN SDK-ALIF REPO WITH SHA/COMMIT-ID/PULL-NUMBER ✏️"
                          }'
                    '''

                    sh '''
                    curl -sS -o /dev/null -X POST "https://api.github.com/repos/${GITHUB_USER_OR_ORG_NAME}/${GITHUB_REPO_NAME}/issues/${CHANGE_ID}/labels" \
                      -H "Authorization: Bearer ${GITHUB_TOKEN}" \
                      -H "Content-Type: text/plain" \
                      -d '["BUILD_AWAITING"]'
                    '''
                }
            }
        }

        cleanup {
            echo "Cleaning up workspace..."
            deleteDir()
        }
    }
}
